

# PERSONALIZATION
# Site variables
name: Centro Comunitário A-Sol
# og: assets/img/og.png
logo: /assets/img/logo.png
original_repo: https://github.com/hackupc/hackersatupc.org
description: Centro Comunitário A-Sol
ga: 
domain: hackersatupc.org


# Style variables
accent_color: "#F44336"
events_overlay_color: "#F1C232"
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/people.jpg

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: Hackers@UPC
author-description: "Hackers@UPC is a student organization at Universitat Politècnica de Catalunya who brings together
    people for our technology and design event: HackUPC. Our mission is to foster learning, designing, and building in order to turn student's ideas into a reality!"
email: contact@hackersatupc.org

# Social media + community variables
twitter: hackersupc
fb: hackersatupc
fb-community: hackersatupc

# instagram: hackcu
github-org: hackupc



# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Madrid
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:+0100
  TZOFFSETTO:+0200
  TZNAME:CEST
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=4SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:+0200
  TZOFFSETTO:+0100
  TZNAME:CET
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=4SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
